// Este archivo es el encabezado de la aplicación Next.js.
// Contiene la configuración de fuentes, metadatos y el diseño general de la aplicación.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fixall App",
  description: "Generated by Talento Tech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 shadow-md p-4 flex justify-between items-center">
          <Link href="/" className="text-2xl font-bold text-white hover:text-blue-600">
          Fixall
          </Link>
          <div className="space-x-6">
            <Link href="/auth/service" className="text-white hover:text-blue-600">
            Servicios
            </Link>
            <Link href="/auth/signup" className="text-white hover:text-blue-600">
            Registrarse
            </Link>
            <Link href="/auth/creadores" className="text-white hover:text-blue-600">
             Nuestro equipo
            </Link>
            <Link href="/auth/logintc" className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">
            Login
            </Link>
          </div>
        </nav>
        <div>
        {children}

        </div>
        
      </body>
    </html>
  );
}
